name: CI
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    environment: golang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/setup-buildx-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/golang:latest

  deployment:
    needs: build
    environment: golang
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{secrets.SERVER_PORT}}
          script: |
            whoami
            docker stop golang || true && docker rm golang || true
            docker pull ${{vars.IMAGE_NAME}}
            docker run -d -p 8080:8080 --name ${{vars.CONTAINER_NAME}} ${{vars.IMAGE_NAME}}
